--- #YAML:1.0
name: Apache-OneTimeURL
version: 1.1
license: perl
distribution_type: module
requires:
  Apache: 0
  DB_File: 0
  Digest::MD5: 0
  MLDBM: 0
  Mail::Send: 0
  perl: 5.6.0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Apache::OneTimeURL:
    file: lib/Apache/OneTimeURL.pm
    version: 1.1
generated_by: Module::Build version 0.19
